::: pyagenity.exceptions.recursion_error
